# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Novice's Nook
tagline:          'A blog in which I write my experiences with learning new things'
description:      'By <a href="https://twitter.com/Abhay_Kaushik_/" target="_blank">@Abhay_Kaushik_</a>'
url:              http://abhaykaushik.github.io
baseurl:          /

author:
  name:           'Abhay Kaushik'
#  url:            https://twitter.com/Abhay_Kaushik_/

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/AbhayKaushik
